language: node_js
node_js: '9'
services:
- mongodb
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $jhobfhjblfd8972hkj -iv $jhobfhjblfd8972hkj
  -in do-deployPPK.enc -out do-deployPPK -d
- bash _scripts/install.sh
after_success:
  - bash _scripts/deploy.sh
