language: node_js
node_js: '9'
services:
- mongodb
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_f3ed88e737e6_key -iv $encrypted_f3ed88e737e6_iv
  -in do-deployPPK.enc -out do-deployPPK -d
- openssl aes-256-cbc -K $password -in do-deployPPK.enc -out do-deployPPK -iv $password
  -d
- bash _scripts/install.sh
after_success:
- bash _scripts/deploy.sh
env:
  global:
    secure: aQvGo+xEUwgb2e0WqwKL4QV2IruEM+Fw/FLydn2+hbmmjLd1HKVZX8ofPsuQW9cHYMKaDoj5mzWSr0vWQ3PUf6RpGyOv9u2os391wpxHGOFgQqvV/O7llVfZ+gvKdVnUszAdVdIpbB//dY6Ok4LDHbdD9F950l7o5YjN7UD9VVsXYU+tAAmyja3cVzjHf0CLT6FlAeJbt0UCDE+5comNnwzW1s5JJI3mzdoRnDkg4S8kafotp4dT/HsU3gnE7e/cswiPNZp1uWmdfzrnZHNaOjat0nv0MtEYei1YnvWSFEGHTRVPjGdRmTo1iXmUd2kAcY6mw8Zf0mO4BIcJLCVPZxOfHn4I6S5oD07A35YGUnBjjOxuHOuFkdEvR1Syh9km8FaGK2gybTv97EujK/dEfe8uqkB8H9UnLoS0T9AEwSETSERN6ucHm5Q6ZALscc8lIM1LCkuthcrfvdmlOhz3QV0XFRofLPcKSarMhZJF7czIBXkQp/BcvrfeyNbxO7r4OupaaaE71NDQcEYGD+SLuvYrPy6tnsiQnTIzz+njsb9RYb2MgoUVbFze1a2PmA4c+08mMfq+Bl7p93PskSqMdPMobLLf2I3Le2pOAK3bfcQsqkIrpQXKqwaUxU0b07DyaFbiLJgcvPljgwLYCJpkaobklWiRVXeV+yGJ+msXQ8U=
