version: "3"
services:
  # app:
  #   container_name: server
  #   build: .
  #   ports:
  #     - "3000:3000"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    # links:
    #   - mongo
#   mongo:
#     container_name: mongo
#     image: mongo
#     volumes:
#       - mongodata:/data/db
#     ports:
#       - "27017:27017"
# volumes:
#   mongodata: